/**
 * 
 */
package supercars.services.inventory;

import java.io.IOException;
import java.util.Collection;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import supercars.Manufacturer;
import supercars.dataloader.ManufacturerDataLoader;
import supercars.utils.json.JSONArray;

/**
 * @author james
 *
 */
public class InventoryServlet extends HttpServlet {

	/**
	 * 
	 */
	private static final long serialVersionUID = -918705794873331672L;

	/**
	 * 
	 */
	public InventoryServlet() {
		
	}
	
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
    	
		try {
			
			System.out.println("!!!!!!!!!!!!!!!! Inventory Service Recieved Request URI: " + request.getRequestURI());
			
			String reqUri = request.getRequestURI();
	    	
	    	if (reqUri.equals("/inventory/manufacturers")) {
	    		
					
	    		ManufacturerDataLoader mdl = new ManufacturerDataLoader();
	    		Collection<Manufacturer> result = mdl.getManufacturers();
	    		JSONArray jsonArray = new JSONArray(result);
	    		
	    		String json = jsonArray.toString(4);
					
			    System.out.println("!!!!!!!!!!!!!!!! JSON Payload generated by Inventory Service " + request.getRequestURI());
			    System.out.println(json);
					
			    response.setContentType("application/json");
			    response.setStatus(HttpServletResponse.SC_OK);
			    response.getWriter().println(json);

	    	} else {
	    		System.out.println("!!!!!!!!!!!!!!!! Inventory Service URI HAD NO MATCH: " + request.getRequestURI());
	    		
	            response.setContentType("application/json");
	            response.setStatus(HttpServletResponse.SC_OK);
	            response.getWriter().println("{ \"status\": \"ok\"}");	    		
	    	}
			
		} catch (Throwable ex) {
			System.out.println("########################## Inventory Service Failure ##########################");
			System.out.println("########################## " + ex.getMessage() + " ##########################");
			ex.printStackTrace();
				
		}
		
    	
    }
    
    
}
