/**
 * 
 */
package supercars.services.enquiry;

import java.io.IOException;
import java.util.Collection;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import supercars.dataloader.EnquiryDataLoader;
import supercars.utils.json.JSONArray;

/**
 * @author james
 *
 */
public class EnquiryServlet extends HttpServlet {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7988011897341720634L;
	private static Log log = LogFactory.getLog(EnquiryServlet.class);
	
	private static int ERROR_COUNT = 0;

	/**
	 * 
	 */
	public EnquiryServlet() {
		
	}

	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		
		
		try {
			
			log.info("!!!!!!!!!!!!!!!! Enquiry Service Recieved Request URI: " + request.getRequestURI());

    		String reqUri = request.getRequestURI();
    		
    		if (reqUri.startsWith("/enquiry/carEnquiries")) {

    			String carId = request.getParameter("carId");
        		log.info("########################## Enquiry Service recieved REQ Param carId = " + carId + " ##########################");
    			
    			Collection result = new EnquiryDataLoader().getEnquirysForCar(Integer.parseInt(carId));
	    		JSONArray jsonArray = new JSONArray(result);
	    		
	    		String json = jsonArray.toString(4);
					
			    log.info("!!!!!!!!!!!!!!!! JSON Payload generated by Enquiry Service " + request.getRequestURI());
			    log.info(json);
	
			    
			    response.setContentType("application/json");
			    response.setStatus(HttpServletResponse.SC_OK);
			    response.getWriter().println(json);
    			
    			
			    
	    	} else {
	    		
	    		log.info("!!!!!!!!!!!!!!!! Enquiry Service URI HAD NO MATCH: " + request.getRequestURI());
	    		
	            response.setContentType("application/json");
	            response.setStatus(HttpServletResponse.SC_OK);
	            response.getWriter().println("{ \"status\": \"ok\"}");	    		
	    	}
    		
//			String url = "https://ratekick.com/";
//			HttpClient client = HttpClientBuilder.create().build();
//			
//			HttpGet req = new HttpGet(url);
//			HttpResponse res = client.execute(req);
//			res.getStatusLine();
			
			response.setContentType("application/json");
			response.setStatus(HttpServletResponse.SC_OK);
			response.getWriter().println("{ \"status\": \"ok\"}");	  				


		} catch (Throwable ex) {
			log.info("########################## Enquiry Service Failure ##########################");
			log.error("########################## " + ex.getMessage() + " ##########################", ex);
			ex.printStackTrace();
				
		}
		

    }

    
}
